# Generated by Django 4.0.2 on 2022-02-23 04:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Brand Name must be greater than 2 characters')], verbose_name='Name')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Brand Slug must be greater than 2 characters')], verbose_name='Slug')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, max_length=250, null=True, verbose_name='Website')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Category Name must be greater than 2 characters')], verbose_name='Name')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Category Slug must be greater than 2 characters')], verbose_name='Slug')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Product Name must be greater than 2 characters')], verbose_name='Name')),
                ('slug', models.SlugField(max_length=70, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Product Slug must be greater than 2 characters')], verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Short Description')),
                ('long_description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(15000, 'The value is too long.')], verbose_name='Detailed Description')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Price must be greater than 0.'), django.core.validators.MaxValueValidator(1000000, 'Price must be less than 1000000.')], verbose_name='Price')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Stock must be greater than 0.'), django.core.validators.MaxValueValidator(5000, 'Stock must be less than 5000.')], verbose_name='Stock')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Out of Stock', 'Out of Stock')], default='Active', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator.category', verbose_name='Category')),
            ],
        ),
    ]
